name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install aws-cdk
        run: npm install -g aws-cdk

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test (Release)
        run: dotnet test --configuration Release --no-build --verbosity normal --blame-hang --blame-hang-timeout 15m --filter "Category!=LiveIntegration"
        env:
          CDK_BOOTSTRAP_TIMEOUT_MINUTES: 10
